### ISSUE TITLE
DB Schema - Design, Domain & Table details

### ISSUE THREAD

**Issue by murugan425** [next-demo/doctor-appointment-service#4]
- [x] Identify the domains.
- [x] List of db tables to be created.
- [x] Generate the DDL scripts
- [x] Setup a common database.
- [ ] Provide access to the team members.

**Comment by sdkosm** [comment]
Four task completed #4

**Comment by sdkosm** [comment]
**### SOME SQL COMMAND FOR DATABASE:** 

-- create database docapp;
-- use docapp;
-- create table Location(location_id int, location_name varchar(20), primary key (location_id) );
-- show databases
-- show schemas;
-- select location_id from location;
-- show tables;
-- create table Location(location_id int, location_name varchar(20) )
-- drop table Slot;
-- create table Specialization(spec_id int, spec_name varchar(20), primary key (spec_id) );
-- create table Slot(slot_id int, slot_date varchar(20), primary key (slot_id) );
-- create table Slot(slot_id int, slot_date date, slot_time time(6),  primary key (slot_id) );

-- create table Doctor(doctor_id int primary key,
--  doctor_name varchar(20), 
--  spec_id int,
--  location_id int,
--   foreign key(spec_id) references specialization(spec_id),
--   foreign key(location_id) references location(location_id)
--  )
 
 
--  create table Appointment(
--  appointment_id int primary key,
--  patient_name varchar(20), 
--  patient_contact varchar(20),
--  patient_email varchar(15),
--  patient_dob date,
--  patient_gender varchar(8),
--  doctor_id int,
--  slot_id int,
--   foreign key(doctor_id) references doctor(doctor_id),
--   foreign key(slot_id) references slot(slot_id)
--  )doctor_id

--  create table User(
--  user_id int primary key,
--  user_name varchar(20), 
--  user_email varchar(15),
--  user_password varchar(20),
--  appointment_id int,
--   foreign key(appointment_id) references appointment(appointment_id)
--  )

**THIS IS FOR GENERATE DDL SCRIPT:**

-- show create table doctor;
-- show create table appointment;
-- show create table location;
-- show create table slot;
-- show create table specialization;
-- show create table user;

**Comment by sdkosm** [comment]
<HTML>
<BODY>
<TABLE><TR><TD>CREATE TABLE `doctor` ( &nbsp;&nbsp;`doctor_id` int NOT NULL, &nbsp;&nbsp;`doctor_name` varchar(20) DEFAULT NULL, &nbsp;&nbsp;`spec_id` int DEFAULT NULL, &nbsp;&nbsp;`location_id` int DEFAULT NULL, &nbsp;&nbsp;PRIMARY KEY (`doctor_id`), &nbsp;&nbsp;KEY `spec_id` (`spec_id`), &nbsp;&nbsp;KEY `location_id` (`location_id`), &nbsp;&nbsp;CONSTRAINT `doctor_ibfk_1` FOREIGN KEY (`spec_id`) REFERENCES `specialization` (`spec_id`), &nbsp;&nbsp;CONSTRAINT `doctor_ibfk_2` FOREIGN KEY (`location_id`) REFERENCES `location` (`location_id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci</TD></TR></TABLE>

</BODY>
</HTML>

**Comment by sdkosm** [comment]
DDL FOR APPOINTMENT

<HTML>
<BODY>
<TABLE><TR><TD>CREATE TABLE `appointment` ( &nbsp;&nbsp;`appointment_id` int NOT NULL, &nbsp;&nbsp;`patient_name` varchar(20) DEFAULT NULL, &nbsp;&nbsp;`patient_contact` varchar(20) DEFAULT NULL, &nbsp;&nbsp;`patient_email` varchar(15) DEFAULT NULL, &nbsp;&nbsp;`patient_dob` date DEFAULT NULL, &nbsp;&nbsp;`patient_gender` varchar(8) DEFAULT NULL, &nbsp;&nbsp;`doctor_id` int DEFAULT NULL, &nbsp;&nbsp;`slot_id` int DEFAULT NULL, &nbsp;&nbsp;PRIMARY KEY (`appointment_id`), &nbsp;&nbsp;KEY `doctor_id` (`doctor_id`), &nbsp;&nbsp;KEY `slot_id` (`slot_id`), &nbsp;&nbsp;CONSTRAINT `appointment_ibfk_1` FOREIGN KEY (`doctor_id`) REFERENCES `doctor` (`doctor_id`), &nbsp;&nbsp;CONSTRAINT `appointment_ibfk_2` FOREIGN KEY (`slot_id`) REFERENCES `slot` (`slot_id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci</TD></TR></TABLE>

</BODY>
</HTML>

**Comment by sdkosm** [comment]
DDL FOR LOCATION

<HTML>
<BODY>
<TABLE><TR><TD>CREATE TABLE `location` ( &nbsp;&nbsp;`location_id` int NOT NULL, &nbsp;&nbsp;`location_name` varchar(20) DEFAULT NULL, &nbsp;&nbsp;PRIMARY KEY (`location_id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci</TD></TR></TABLE>

</BODY>
</HTML>

**Comment by sdkosm** [comment]
DDL FOR SLOT

<HTML>
<BODY>
<TABLE><TR><TD>CREATE TABLE `slot` ( &nbsp;&nbsp;`slot_id` int NOT NULL, &nbsp;&nbsp;`slot_date` date DEFAULT NULL, &nbsp;&nbsp;`slot_time` time(6) DEFAULT NULL, &nbsp;&nbsp;PRIMARY KEY (`slot_id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci</TD></TR></TABLE>

</BODY>
</HTML>

**Comment by sdkosm** [comment]
DDL FOR SPECIALIZATION

<HTML>
<BODY>
<TABLE><TR><TD>CREATE TABLE `specialization` ( &nbsp;&nbsp;`spec_id` int NOT NULL, &nbsp;&nbsp;`spec_name` varchar(20) DEFAULT NULL, &nbsp;&nbsp;PRIMARY KEY (`spec_id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci</TD></TR></TABLE>

</BODY>
</HTML>

**Comment by sdkosm** [comment]
DDL FOR USER

<HTML>
<BODY>
<TABLE><TR><TD>CREATE TABLE `user` ( &nbsp;&nbsp;`user_id` int NOT NULL, &nbsp;&nbsp;`user_name` varchar(20) DEFAULT NULL, &nbsp;&nbsp;`user_email` varchar(15) DEFAULT NULL, &nbsp;&nbsp;`user_password` varchar(20) DEFAULT NULL, &nbsp;&nbsp;`appointment_id` int DEFAULT NULL, &nbsp;&nbsp;PRIMARY KEY (`user_id`), &nbsp;&nbsp;KEY `appointment_id` (`appointment_id`), &nbsp;&nbsp;CONSTRAINT `user_ibfk_1` FOREIGN KEY (`appointment_id`) REFERENCES `appointment` (`appointment_id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci</TD></TR></TABLE>

</BODY>
</HTML>
