### ISSUE TITLE
DataBase details about user credentials.

### ISSUE THREAD

**Issue by murugan425** [next-demo/doctor-appointment-service#8]

**Comment by sdkosm** [comment]
**Actually, I am facing some issue with MYSQL database or spring  boot application.**
_**What problem ?**_

Everything is fine but spring boot application is unable to create table in database or may be problem with MYSQL database.

**For code check issues #12 #11  #4**

**Comment by sdkosm** [comment]
Team can use this link .....!!
[https://app.getpostman.com/join-team?invite_code=a16cdbb591c2436eab91e10e26b24f47](url)

**Comment by sdkosm** [comment]
@YashChouhan395 you can also use above link for database
